# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
baseurl: ""

# If you're using GitHub pages without custom domain, this is "[github_username].github.io". Prepend with "http://"
url: "http://spru.sr/ah-site"

# The ability to use custom themes.
style:
  theme: "astonhack"

# This will help you track who's visiting your website.
tracking:
  google_analytics: ""

# Let people connect & engage with you through social media.
social:
  twitter_handle: "AstonHack"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "AstonHack | 5/6 November 2016"
  description: "Aston's student hackathon is back for its second year!"
  image:       "http://astonhack.co.uk/images/astonhack-logo-white.png"

# Event information.
event:
  name:        "AstonHack"
  description: "Aston's student hackathon is back for its second year!"
  date:        "5 & 6 November 2016"
  location:    "Aston University, Birmingham, UK"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "red" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    image: "images/astonhack-logo-white.png"
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "http://spru.sr/ah-site/success.html"
#      - text: "Sponsor"
#        href: "mailto:hack@astoncss.co.uk"

  about:
    description: >
      AstonHack is back for its second year!

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing! Attending a hackathon is free! ðŸ˜
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend as hackers.
    - question: "Where is the event?"
      answer: >
        Check in will be in room MB404 at Aston University, Aston Triangle, Birmingham, B4 7ET. Don't worry, we'll have signs so you don't get lost in the labyrinth that is Aston main building!
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes, we stick strongly to the MLH code of conduct. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "Can we sponsor AstonHack?"
      answer: >
        Yes! We'd love for your company to sponsor, and help make this fantastic event possible!
        We would ask all potential sponsors to email us at hack [at] astoncss.co.uk and one of the team will get back to you.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thanks for signing up - you'll hear more closer to the event!

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
