# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
baseurl: ""

# If you're using GitHub pages without custom domain, this is "[github_username].github.io". Prepend with "http://"
url: "https://astonhack.co.uk"

# The ability to use custom themes.
style:
  theme: "astonhack"

# This will help you track who's visiting your website.
tracking:
  google_analytics: ""

# Let people connect & engage with you through social media.
social:
  twitter_handle: "AstonHack"
  facebook_handle: "astonhack"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "AstonHack | 5/6 November 2016"
  description: "Aston's student hackathon is back for its second year!"
  image:       "https://astonhack.co.uk/images/ah-logo-mb-bg.png"

# Event information.
event:
  name:        "AstonHack"
  description: "Aston's student hackathon is back for its second year!"
  date:        "5 & 6 November 2016"
  location:    "Aston University, Birmingham, UK"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    image: "images/astonhack-logo.svg"
    links:
      - text: "Sign up now!"
        href: "https://www.eventbrite.co.uk/e/astonhack-2016-registration-28388772583"

  about:
    description: >
      # AstonHack is back!

      This time we're opening up places for even more student hackers to enjoy 24 hours of designing, coding and making! Whether this will be your first hackathon or your 20th, AstonHack is great for all levels of experience!

  # Sponsors
  sponsors:
    sections:
      gold:
        - image: "images/majestic-logo.png"
          link: "https://majestic.com/"
      silver:
        - image: "images/accenture-logo.png"
          link: "https://www.accenture.com/gb-en"
        - image: "images/crate-logo.png"
          link: "https://crate.io/"
        - image: "images/phoebus-logo.png"
          link: "http://www.phoebus.co.uk/"
      bronze:
        - image: "images/btp-logo.jpg"
          link: "http://www.bostonteaparty.co.uk/"
        - image: "images/dolce-logo.jpg"
          link: "https://dolcelounge-birmingham.co.uk/"
        - image: "images/algolia-logo.png"
          link: "https://www.algolia.com/"
        - image: "images/tech-domains-logo.png"
          link: "http://get.tech/"

  # Partners
  partners:
    sections:
      - image: "https://static.mlh.io/brand-assets/logo/official/mlh-logo-color.svg"
        link: "https://mlh.io/"
      - image: "images/acss-logo.png"
        link: "http://astoncss.co.uk/"
      - image: "images/eas-logo.png"
        link: "http://www.aston.ac.uk/eas/"

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing! Attending a hackathon is free! ðŸ˜
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students over the age of 18 who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend as hackers.
    - question: "Where is the event?"
      answer: >
        Check in will be in room MB404 at Aston University, Aston Triangle, Birmingham, B4 7ET. Don't worry, we'll have signs so you don't get lost in the labyrinth that is Aston main building!
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        They work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes, we stick strongly to the MLH code of conduct. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "Can we sponsor AstonHack?"
      answer: >
        Yes! We'd love for your company to sponsor, and help make this fantastic event possible! You can view our [sponsorship document here](https://astonhack.co.uk/sponsor-letter.pdf).
        We would ask all potential sponsors to email `hack [at] astoncss.co.uk` and one of the team will get back to you.

  footer:
    message: >
      We can't wait to see what you build!
    legal: >
      &copy; 2016 AstonHack. Site by <a href="http://spru.sr">Scott Street</a>, based on <a href="https://github.com/MLH/mlh-hackathon-boilerplate">MLH Hackathon Boilerplate</a>.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thanks for signing up - you'll hear more closer to the event!

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
